import { getImageProps } from "next/image";

import { Enter, EnterLines, EnterRule } from "@/components/motion/Enter";
import { HeroPointer } from "@/components/sections/HeroPointer";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { displayItalic } from "@/lib/fonts/display-italic";
import { images } from "@/lib/images";
import { brand } from "@/lib/site";

// Phones and portrait tablets get a dedicated portrait composition rather than
// a centre crop of the wide desktop photograph.
const PORTRAIT_MEDIA = "(max-width: 767px), (max-width: 1023px) and (orientation: portrait)";
const LANDSCAPE_MEDIA = "(min-width: 1024px), (min-width: 768px) and (orientation: landscape)";

/**
 * Home hero: a photograph that is quietly alive. Everything here is drawn
 * from what is in the picture (see "Hero motion" in styles/globals.css):
 *
 *  - it opens like a room being lit — a dark veil lifts while warm light
 *    blooms from the window and the picture settles back;
 *  - the rain shower runs, with rings where it lands, mist at its base and
 *    steam rising; the bath filler runs, rings spread across the bath and
 *    light shimmers on the water;
 *  - sunlight breathes across the floor, leaf shadows sway over it and dust
 *    hangs in the window light;
 *  - the LED coves glow gently, and on phones the candle flickers;
 *  - the whole picture drifts slowly, eases against the pointer on desktop,
 *    and holds almost still, darkening, while the next section rises over it.
 *
 * The effects are positioned in percentages of the photograph. They pause
 * when the hero is out of view, and with reduced motion the photograph is
 * simply still.
 */
export function Hero() {
  const {
    props: { srcSet: landscapeSrcSet },
  } = getImageProps({ src: images.hero.src, alt: images.hero.alt, sizes: "100vw", quality: 80 });

  const {
    props: { srcSet: portraitSrcSet, ...portrait },
  } = getImageProps({ src: images.heroPortrait.src, alt: images.hero.alt, sizes: "100vw", quality: 80 });

  return (
    <section data-hero="" className="on-dark relative isolate flex min-h-svh flex-col justify-end overflow-clip bg-espresso text-ivory">
      {/* The hero photograph is the LCP element: preload the right crop for the device. */}
      <link rel="preload" as="image" imageSrcSet={portraitSrcSet} imageSizes="100vw" media={PORTRAIT_MEDIA} fetchPriority="high" />
      <link rel="preload" as="image" imageSrcSet={landscapeSrcSet} imageSizes="100vw" media={LANDSCAPE_MEDIA} fetchPriority="high" />

      <div className="hero-stage">
        <HeroPointer>
          <div className="hero-scroll">
            <div className="hero-settle">
              <div className="hero-drift">
                {/* Sized to the proportions of the photograph, so the effects below stay locked to it. */}
                <div className="hero-frame">
                  <picture>
                    <source media={LANDSCAPE_MEDIA} srcSet={landscapeSrcSet} sizes="100vw" />
                    <source media={PORTRAIT_MEDIA} srcSet={portraitSrcSet} sizes="100vw" />
                    {/* Art-directed <picture>: both sources are generated by next/image. */}
                    <img
                      {...portrait}
                      alt={images.hero.alt}
                      loading="eager"
                      fetchPriority="high"
                      decoding="sync"
                      className="size-full object-cover"
                      style={undefined}
                    />
                  </picture>

                  <div aria-hidden="true" className="hero-fx">
                    {/* Light */}
                    <div className="hero-sun" />
                    <div className="hero-leaves">
                      <span />
                      <span />
                    </div>
                    <div className="hero-glow hero-glow-cove" />
                    <div className="hero-glow hero-glow-niche" />
                    <div className="hero-glow hero-glow-mirror" />
                    <div className="hero-glow hero-glow-floor" />
                    <div className="hero-candle" />

                    {/* Shower */}
                    <div className="hero-steam hero-steam-shower">
                      <span />
                      <span />
                    </div>
                    <div className="hero-water hero-water-shower">
                      <span />
                      <span />
                      <span />
                    </div>
                    <div className="hero-ripple hero-ripple-shower">
                      <span />
                      <span />
                      <span />
                    </div>
                    <div className="hero-mist" />

                    {/* Bath */}
                    <div className="hero-steam hero-steam-bath">
                      <span />
                      <span />
                    </div>
                    <div className="hero-shimmer">
                      <span />
                    </div>
                    <div className="hero-water hero-water-filler">
                      <span />
                    </div>
                    <div className="hero-ripple hero-ripple-bath">
                      <span />
                      <span />
                      <span />
                    </div>

                    {/* Air */}
                    <div className="hero-motes">
                      <span />
                      <span />
                      <span />
                      <span />
                      <span />
                      <span />
                      <span />
                      <span />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </HeroPointer>

        {/* Scroll: the room darkens as the next section rises over it. */}
        <div aria-hidden="true" className="hero-dim" />

        {/* Opening: warm light blooms from the window as a dark veil lifts. */}
        <div aria-hidden="true" className="hero-bloom" />
        <div aria-hidden="true" className="hero-veil" />
      </div>

      {/* Warm, neutral toning only — no colour wash: a light overall tone, a band behind the header and a base for the type. */}
      <div aria-hidden="true" className="absolute inset-0 -z-10 bg-espresso/10" />
      <div
        aria-hidden="true"
        className="absolute inset-x-0 top-0 -z-10 h-40 bg-linear-to-b from-espresso/65 to-transparent"
      />
      <div
        aria-hidden="true"
        className="absolute inset-x-0 bottom-0 -z-10 h-[82%] bg-linear-to-t from-espresso from-[4%] via-espresso/65 via-[46%] to-transparent md:h-[74%] md:via-espresso/45 md:via-[40%]"
      />

      {/* On phones the bottom padding clears the fixed action bar. */}
      <div className="hero-content container-site relative pt-32 pb-[calc(4rem+env(safe-area-inset-bottom)+1.75rem)] md:pb-14 lg:pb-16">
        <div className="lg:grid lg:grid-cols-12 lg:items-end lg:gap-x-10">
          <div className="lg:col-span-9">
            <Enter delay={0.1} y={14}>
              <p className="hero-legible eyebrow flex flex-col gap-1 text-ivory/90 sm:flex-row sm:items-center sm:gap-4">
                <span>Premium Sanitaryware</span>
                <span aria-hidden="true" className="hidden h-px w-8 bg-amber sm:block" />
                <span>Dhakoli • Zirakpur</span>
              </p>
            </Enter>

            <h1 className="hero-legible text-display mt-5 md:mt-7">
              <EnterLines
                lines={["Bathrooms,", "reimagined."]}
                emphasis={1}
                emphasisClassName={displayItalic.className}
                delay={0.2}
                stagger={0.14}
              />
            </h1>

            <Enter delay={0.5} y={20}>
              <p className="hero-legible text-lead mt-6 max-w-[34rem] text-ivory/90 md:mt-8">
                Premium sanitaryware, bathroom fittings, faucets, showers and complete bathroom solutions for
                contemporary spaces.
              </p>
            </Enter>

            <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:gap-4 md:mt-10">
              <Enter delay={0.62} y={16} className="flex flex-col">
                <ButtonLink href="/products" variant="ivory">
                  Explore Collection
                </ButtonLink>
              </Enter>
              <Enter delay={0.72} y={16} className="flex flex-col">
                <ButtonLink href="/location" variant="outline-light">
                  Visit Showroom
                </ButtonLink>
              </Enter>
            </div>
          </div>

          <div className="mt-10 hidden items-end justify-between gap-8 md:flex lg:col-span-3 lg:mt-0 lg:flex-col lg:items-end lg:justify-end lg:gap-10">
            <Enter delay={0.95} y={0}>
              <p className="hero-legible eyebrow text-ivory/80 lg:text-right">{brand} Products Available</p>
            </Enter>
            <Enter delay={1.1} y={0}>
              <a
                href="#introduction"
                className="hero-legible eyebrow group inline-flex min-h-11 items-center gap-4 text-ivory/80 transition-colors duration-300 hover:text-ivory"
              >
                <span>Scroll to explore</span>
                <span aria-hidden="true" className="relative block h-12 w-px overflow-clip bg-ivory/20">
                  <span className="animate-scroll-cue absolute inset-0 bg-amber" />
                </span>
              </a>
            </Enter>
          </div>
        </div>

        <EnterRule delay={0.8} className="mt-10 hidden h-px w-full bg-ivory/20 md:block lg:mt-14" />
      </div>
    </section>
  );
}
